- .travis.yml
- conda-recipe/meta.yaml
- dev-requirements.txt
- docs/Makefile
- docs/source/log_setup.rst
- hutch_python/log_setup.py
- test-requirements.txt
- Check the conda recipe as part of the CI
- Install the built package to pick up dependencies
- conda config --add channels
- Simplify the log initialization so that it works on more systems. This was causing my weird docs build error.
- Avoid breaking conda recipe, encourage keeping the requirements accurate
- The travis yml file gets verbose with channels and run requirements, this eliminates that
- I like conda more than pip
> CI: Conda build and misc fixes

- hutch_python/base_plugin.py
- hutch_python/load_conf.py
- hutch_python/log_setup.py
- hutch_python/plugins/namespace.py
- hutch_python/tests/conftest.py
- hutch_python/tests/sample_module_1.py
- hutch_python/tests/test_base_plugin.py
- hutch_python/tests/test_cli.py
- hutch_python/tests/test_load_conf.py
- hutch_python/tests/test_log_setup.py
- hutch_python/tests/test_plugins/test_experiment.py
- hutch_python/tests/test_plugins/test_namespace.py
- hutch_python/tests/test_utils.py
- hutch_python/utils.py
- logging.yml
- run_tests.py
- Mild refactoring so I can test every line
- 100% coverage
- Subtle bugs found/fixed in the 100% coverage crusade
- Nitpick the logging setup
The top-level user interface needs to be very bug-free. Coverage is the first step to doing that.
closes #18
> TST: Full Coverage

- .travis.yml
`anaconda-client` was never installed
> FIX: Install anaconda-client

- dev-requirements.txt
- docs/source/yaml_files.rst
- hutch_python/plugins/questionnaire.py
- hutch_python/tests/conftest.py
- hutch_python/tests/test_plugins/test_questionnaire.py
Use the `QSBackend` to load information from the PCDS Questionnaire. Depends on the `experiment` section of the YAML file, specifically `proposal` and `run`
Closes #30
Added a slightly convoluted test to load a custom device that allows us to check the internals of the Backend.
Module level docstring added to Sphinx
> ENH: Questionnaire Plugin

- .travis.yml
- README.rst
- conda-recipe/meta.yaml
- hutch_python/load_conf.py
Work in progress, accumulating changes as we find issues live.
- catch errors in pre_plugin load
- allow the use of a default class checking path for the namespace plugins
- add HUTCH BANNERS
> WIP: More Fixes

- .travis.yml
- README.rst
- conda-recipe/meta.yaml
- hutch_python/happi.py
- hutch_python/load_conf.py
- hutch_python/tests/happi_db.json
- hutch_python/tests/test_happi.py
- hutch_python/tests/test_load_conf.py
Loads a `lightpath.BeamPath` object with the name `{hutch}_beampath`. Adds a dependency on the `lightpath` module which in turn needs `PyDM`
* Added a specific test for the `get_lightpath` function
* Added a check in `test_load_conf` that it gets executed properly when loading the entire configuration
Updated module docstring for `hutch_python.happi`
> ENH: Lightpath

- hutch_python/cookiecutter/{{ cookiecutter.hutch }}/.gitignore
Ignore `hutch/db.txt` file that is generated every time `hutch_python` is loaded.
> DEV: Ignore generated db.txt file

- README.rst
- docs/source/yaml_files.rst
- add newline to get correct bullet-point list
- fix docs link in readme
> DOC: fix typos

- docs/source/hutch_setup.rst
Added a short blurb in the hutch setup section about how to go about best practices for adding new devices to the database. This was unclear and it is probably best to point new `happi` users away from modifying the main database to start.
Per conversation with @silkenelson
> DOC: Clarify procedure for adding devices

- hutch_python/load_conf.py
Puts the banner as early as we can feasibly do it
closes #102
> FIX: Hutch banner asap to minimize chance of prints before it

- docs/source/index.rst
- docs/source/tips.rst
There isn't much here yet, but I want there to be a clear place to include these.
closes #83
> DOC: Start the tips page

- hutch_python/cli.py
- hutch_python/constants.py
- hutch_python/cookiecutter/cookiecutter.json
- hutch_python/cookiecutter/{{ cookiecutter.hutch }}/{{ cookiecutter.hutch }}version
- hutch_python/tests/test_cli.py
- Build the `hutchversion` file in the cookiecutter with the last updated version in the live directory.
- Fall back to the user's current conda environment if the live directory doesn't exist (e.g. dev checkout)
- Set up logging before cookie cutter
- I don't want to keep updating the cookie cutter for version numbers of `pcds-envs` and I found a way to stop doing it
Added tests and works on `psbuild-rhel6`
> MNT: No hardcoding in cookiecutter

- conda-recipe/meta.yaml
- docs/source/daq.rst
- docs/source/index.rst
- docs/source/releases.rst
- docs/source/startup.rst
- hutch_python/load_conf.py
- hutch_python/tests/test_load_conf.py
Import and include. Leave disabled to avoid two sessions fighting over the pvs.
closes #90 
closes #131 
Added include test, made sure it connects for XCS
Would you believe I forgot? I guess I'll go back and add it.
> ENH: Scan pvs

- .travis.yml
- docs/source/startup.rst
- hutch_python/cam_load.py
- hutch_python/constants.py
- hutch_python/load_conf.py
- hutch_python/tests/camviewer.cfg
- hutch_python/tests/conftest.py
- hutch_python/tests/test_cam_load.py
- hutch_python/tests/test_load_conf.py
Load camviewer.cfg file and create detector objects for the hutch
closes #117 
Added tests
Small note in docs and docstrings
> ENH: Camviewer Cams

- docs/source/releases.rst
It's been more than a month since the last release, and this isn't being actively worked on. It's time for a tag.
> DOC: add 0.7.0 release notes

- conda-recipe/meta.yaml
- hutch_python/exp_load.py
- hutch_python/load_conf.py
- hutch_python/qs_load.py
- hutch_python/tests/conf.yaml
- hutch_python/tests/conftest.py
- hutch_python/tests/test_experiment.py
- hutch_python/tests/test_questionnaire.py
See https://github.com/pcdshub/happi/pull/68
I still need to edit the docs about changes to the conf.yaml experiment override.
This will of course not work until the above PR is finished.
> ENH: Update for new QS

- .travis.yml
- hutch_python/bug.py
- hutch_python/cam_load.py
- hutch_python/tests/conftest.py
- Fix the test so that the dev build passes for now
- Make the dev build ok to fail
- Add python 3.7 builds. These will fail for a while because they depend on nearly everything else, but since I was here...
Testing issue caused dev build to fail, marking my other PR as failed. Decided to fix it in a separate PR rather than bundling with the first.
See Travis
n/a
> TST: Fix tests, update CI

- docs/source/releases.rst
> DOC: create 1.0.1 release notes

- conda-recipe/meta.yaml
- hutch_python/cam_load.py
- hutch_python/tests/conftest.py
- hutch_python/tests/test_cam_load.py
Match the new pcdsdevices API
The API changed, see https://github.com/pcdshub/pcdsdevices/pull/330
> FIX: compatibility with pcdsdevices 2.0.0

- hutch_python/cookiecutter/{{ cookiecutter.hutch }}/set-dev
- hutch_python/cookiecutter/{{ cookiecutter.hutch }}/{{ cookiecutter.hutch }}env
- hutch_python/tests/test_cli.py
- update version on default env
- switch set-env to ssh
> ENH: update cookiecutter

- conda-recipe/meta.yaml
- hutch_python/happi.py
- hutch_python/tests/conftest.py
We're generalizing and cleaning up `happi`, so some API is changing. This adjusts `hutch-python` for it.
Tested locally with dev builds until a release of happi + lightpath
attn @klauer @hhslepicka 
There might be some need for a `DummyBackend` for stuff like the conftest hack that failed here
> MNT: happi API changes

- conda-recipe/meta.yaml
- hutch_python/log_setup.py
Set up this logger at the application level for any user code that sends messages to logstash
Logging configuration is the responsibility of the application to maximize library portability
> ENH: use pcdsutils to configure logstash logger

- docs/source/releases.rst
> DOC: add release notes

- docs/source/releases.rst
Tag would contain minor fixes/features from me
> DOC: add release notes for v1.3.0 and for skipped releases

- hutch_python/tests/test_bug.py
Minor fix - saw this in #206 CI
> TST: log message woops

- docs/source/releases.rst
> DOC: add release notes for v1.4.0

- .travis.yml
- conda-recipe/meta.yaml
- dev-requirements.txt
- docs/source/cli.rst
Switch to using pcds-ci-helpers in the travis file
Long overdue + sidestep a travis setup bug in the original config
CI works
> ENH: pcds-ci-helpers usage

- hutch_python/load_conf.py
Add a class namespace that accumulates the AmiDet objects, as in old python
Closes #212
> ENH: add class namespace for ami detectors

- hutch_python/load_conf.py
- hutch_python/sim.py
Add three fast motors that reach the destination immediately
Add three slow motors that reach the destination slowly
closes #208
Locally
> ENH: add a few simulated motors by default

- docs/source/releases.rst
> DOC: add release notes for v1.6.0

- docs/source/releases.rst
User file loading fixes from @klauer
> DOC: add notes for release and previous

- .pre-commit-config.yaml
- conda-recipe/meta.yaml
- hutch_python/lcls.py
- hutch_python/load_conf.py
- setup.cfg
A bunch of small additions/fixes all in one PR:
- LCLS object
- BeamStats object
- Fix load order so beamline and experiment files happen as late as possible
- Enable scan PVs for all consumers
- closes #152
- closes #189 
- closes #241
- closes #242
TBH I have not tested this yet, one sec
> ENH: LCLS, BeamStats, Load Order, Scan PVs

- docs/source/releases.rst
Small tag
Probably another one next week when we put the calcs in
> DOC: write release notes for v1.8.0 tag

- conda-recipe/meta.yaml
- hutch_python/constants.py
- hutch_python/epics_arch.py
- hutch_python/qs_load.py
- hutch_python/tests/test_epics_arch.py
- setup.py
Create a second entry point `epicsarch-qs` that will handle creating the `epicsArch` file from the Questionnaire.
Trying to implement and close https://github.com/pcdshub/Bug-Reports-and-Requests/issues/52
Locally only.
> ENH: initial setup add epicsarch-qs cmd script

- hutch_python/cookiecutter/{{ cookiecutter.hutch }}/{{ cookiecutter.hutch }}env
- Update template's version to latest
- Include local hard drive loading
- Add various dev comments
- Might as well clean up here before making the next new one
- closes #251 
- works toward #252 
Runs as expected after creating a new tstpython in a test area on psbuild-rhel7-01
> ENH: update, rework, and document env template

- docs/source/releases.rst
End of the year tagging season
> DOC: write release notes for v1.9.0

- hutch_python/load_conf.py
Add the best-effort-callback into the normal namespace
Ignore the question of "should we collect all the configurable things into a `config` object" for now
closes #261 
low-hanging-fruit day for environment tag
n/a
Will be in release notes
> ENH: include bec in namespace

- docs/source/releases.rst
- hutch_python/cache.py
- hutch_python/calc_defaults.py
- hutch_python/cli.py
- hutch_python/debug.py
- hutch_python/lcls.py
- hutch_python/load_conf.py
- hutch_python/options.py
- hutch_python/sim.py
- hutch_python/utils.py
- Annotate load_conf.py with docs for each item added
- Make sure these doc strings get included in the namespace table summaries
- Reorganize so that all items are added to the cache in the same way (previously, some debug utilities and misc were strapped on after the normal load process)
- Need some top-level documentation as a companion to #267 which works great for everything that isn't too generic
- E.g. namespaces will now have  quick blurb about what exactly they are namespaces for
- Existing tests still pass
- Expanded release notes
> ENH: load_cache doc annotations

- docs/source/releases.rst
Small release to maybe hit an environment tag today
> DOC: add release notes for v1.10.1

- docs/source/releases.rst
Release notes for tag today
We fixed a bug here and I want to deploy a bunch of updates early next week
> DOC: add v1.11.1 release notes

- MANIFEST.in
- requirements.txt
- setup.py
Closes #284 - for the most part
My quick test indicated _at least_ some work is needed on lightpath on PyPI at the moment. (https://github.com/pcdshub/lightpath/issues/124)
> BLD: update pip requirements, manifest, and general setup things

- docs/source/releases.rst
- hutch_python/happi.py
- hutch_python/load_conf.py
- release notes
- make elog and lightpath optional to match the updated requirements.txt
- other modules are being tagged, let's tag here too
- let's clean up the optional deps if we are tagging, should be able to run this from pip for dev
- interactively only to make sure the user warning messages looked correct
- release notes
> DOC: v1.11.2, MNT: optional deps

- conda-recipe/meta.yaml
- docs/source/releases.rst
- closes #295 
- adds release notes for the log filtering tag
> DOC: v1.13.0 release notes

- docs/source/releases.rst
Document various bugfixes and maintenance for tag
Tagging everything for the pamm
This is documentation
This is documentation
> DOC: add release notes for v1.13.1

- docs/source/releases.rst
I want to tag this small tweak and release a small update to our conda env
> DOC: release notes for patch v1.13.2

- hutch_python/happi.py
Enables per-device load times above a threshold.
Pairs with https://github.com/pcdshub/happi/pull/236
Devices can take a long time to load, and it should not require much digging on the user's part to find it - and help report it to us.
Running xcspython and looking at its output.
This PR text.
<details>
```code
INFO     load_device - Loading at1l0 [pcdsdevices.attenuator.FeeAtt] ...  SUCCESS!
INFO     load_device - Loading at2l0 [pcdsdevices.attenuator.FEESolidAttenuator] ...  SUCCESS! (2.1 s)
INFO     load_device - Loading at2l0_calc [pcdsdevices.attenuator.AttenuatorCalculator_AT2L0] ...  SUCCESS!
INFO     load_device - Loading bt2l0_pleg_vgc01 [pcdsdevices.valve.VGC] ...  SUCCESS!
INFO     load_device - Loading em1l0 [pcdsdevices.energy_monitor.GEM] ...  SUCCESS!
INFO     load_device …
```
> ENH: include per-device load time if available

- docs/source/releases.rst
Contributions from myself, @klauer, and @tangkong 
I want to make a tag
> DOC: write release notes for v1.14.0

- docs/source/releases.rst
Contains #330 and #333
Env tag coming soon
> DOC: add release notes for v1.15.0

- conda-recipe/meta.yaml
- requirements.txt
pyqt breaks ci if >=5.15
I want my builds to pass
CI Take the wheel
This PR
> BLD: pin pyqt<5.15

- docs/source/releases.rst
https://github.com/pcdshub/hutch-python/compare/v1.16.0...master
> DOC: add release notes for v1.17.0

- .travis.yml
- dev-requirements.txt
- docs/pre-release-notes.sh
- docs/release_notes.py
- docs/source/upcoming_release_notes/350-mnt_new_lp_config.rst
- docs/source/upcoming_release_notes/template-full.rst
- docs/source/upcoming_release_notes/template-short.rst
- hutch_python/happi.py
- hutch_python/load_conf.py
- hutch_python/tests/conftest.py
- hutch_python/tests/happi_db.json
- hutch_python/tests/test_cam_load.py
- hutch_python/tests/test_happi.py
- hutch_python/tests/test_tstpython.py
- updates the load database step to use new lightpath functionality
Closes #349 
Should only be merged once other lightpath-related PR's are merged (eg pcdsdevices#1028)
Currently seems to cause a slowdown that I have not isolated.  It may be to an increased number of devices being loaded, but testing has not been comprehensive
interactively, with quite a bit of pathmunging
This PR
> MNT: update lightpath use for object database loading

- CONTRIBUTING.rst
Performed by pcds-migration-tools AddFileFromTemplate
URLs were incorrect from the cookiecutter by accident due to dashes vs underscores
Fixes #359
> MNT: updating CONTRIBUTING.rst from template

- conda-recipe/meta.yaml
- docs/source/releases.rst
> FIX: set the package name back to the original

- docs/source/releases.rst
- hutch_python/epics_arch.py
Release notes for v1.19.0
If I got the descriptions of the EpicsArch wrong in the release notes, let me know
tag
N/A
this PR is release notes
> REL: v1.19.0

- docs/hutch_python.ipynb
- docs/source/upcoming_release_notes/377-doc_jupy_usage.rst
Adds a jupyter notebook with an explanation on how to use hutch-python in jupyter
https://jira.slac.stanford.edu/browse/ECS-4353
All the imports work, but needs more testing
This is docs
> DOC: document how to use hutch-python resources in a jupyter notebook
