- .travis.yml
- conda-recipe/meta.yaml
- hutch_python/base_plugin.py
- hutch_python/load_conf.py
- hutch_python/tests/conf.yaml
- hutch_python/tests/experiments/mfxx000.py
- hutch_python/tests/hutch.py
- hutch_python/tests/test_base_plugin.py
- hutch_python/tests/test_load_conf.py
- hutch_python/tests/test_plugins/test_experiment.py
- hutch_python/tests/test_plugins/test_happi.py
- hutch_python/tests/test_plugins/test_load.py
- hutch_python/tests/test_plugins/test_namespace.py
Plugins are now passed the entire yaml dict. They store this under `self.conf`, and break out their own piece of the dict as `self.info` for convenience.
All bonus dependencies have been removed from the tests. `happi` is still required in the recipe that ships with the module because there is a `happi` plugin, and I expect `happi` to play a role in the upcoming `hutch` plugin.
For the sake of testing, `PCDS_CHANNEL` was swapped from `skywalker-` to `pcds-`
closes #27 
closes #29 
100% coverage
> ENH: More Info for Plugins

- .travis.yml
Deploys built recipes to the PCDS Anaconda channels. Follows the convention we are hoping to standardize on; `pcds-tag` has been cross-checked against only tagged versions of our packages, and `pcds-dev` is using latest.
Closes #32
> CI: Deploy to PCDS Anaconda channels

- hutch_python/__init__.py
- hutch_python/load_conf.py
- hutch_python/tests/conf.yaml
- hutch_python/tests/experiments/mfxx000.py
Instead of `hutch_python.objects`, use a separate namespace for each plugin e.g. `hutch_python.namespace`, `hutch_python.happi`...
This allows us to explicitly find and use groups of loaded objects in later plugin stages e.g. while loading the experiment file.
Passes all old tests.
> API: Change Mid-load Namespacing

- hutch_python/base_plugin.py
- hutch_python/load_conf.py
Overriding `BasePlugin.pre_plugins` to return a list of plugins executes those plugins first, in the order provided.
This allows us to build arbitrary compound plugins from smaller plugin building blocks.
No new tests, not covered. This will be covered for free when we write a metaplugin, and the implementation is simple enough that I'm not worried.
> ENH: Allow Metaplugins

- README.rst
- conda-recipe/meta.yaml
- hutch_python/plugins/beamline.py
- hutch_python/tests/conf.yaml
- hutch_python/tests/test_plugins/test_beamline.py
Add plugin that loads the `Daq` and `RE` objects, and calls the `happi` plugin to load beamline devices.
requires #37
> ENH: Beamline Plugin

- hutch_python/plugins/happi.py
- hutch_python/plugins/questionnaire.py
Setting `pprint=False` will remove the colored loading message coming from happi. I updated the log messages to be more descriptive in their place in https://github.com/slaclab/happi/pull/42
> MAINT: Remove print statements from happi loading

- hutch_python/plugins/questionnaire.py
- hutch_python/tests/conftest.py
- hutch_python/tests/test_plugins/test_questionnaire.py
The `opr` accounts need to have a username and password to login to the LCLS Questionnaires. There isn't a super elegant solution to this problem; we don't want to hard-code the password places, we don't want operators to have to login to hutch python.
This solution searches for a `qs.cfg` file, either in the current directory, hidden in the current directory, or hidden in the user directory. If this file is found, the information contained is used to authenticate. If not found, the user's kerberos ticket is used. Not an incredible solution but it means that:
1) Regular users will just use their Kerberos without thinking about it as long as they don't have a `qs.cfg` file in their home directory
2) Operators can access the Questionnaire and their password is safely hidden in a read-only …
> Authentication Configuration

- .coveragerc
- .travis.yml
- README.rst
- bin/hutch-python
- hutch_python/cli.py
- hutch_python/ipython_log.py
- hutch_python/log_setup.py
- hutch_python/logging.yml
- hutch_python/tests/test_cli.py
- hutch_python/tests/test_ipython_log.py
- hutch_python/tests/test_load_conf.py
- log all IPython input and output in the debug stream
- log all exceptions that bubble up to the top of the IPython terminal to the debug stream
- remove file handlers for all log levels except for debug
- one log file per session
- fix codecov that I broke
This will be very useful for tracking down some of the more obscure bugs when we're trying to figure out how to reproduce them. The redundant logfiles were redundant. One file per session means no user vs user conflicts, and it means we can log two terminal sessions by the same user independently.
`tstpython` passes all the spot-tests, and the automated tests pass.
> LOG: Let's log... almost everything

- hutch_python/cli.py
- hutch_python/ipython_log.py
- hutch_python/log_setup.py
- hutch_python/logging.yml
- hutch_python/tests/conftest.py
- hutch_python/tests/test_cli.py
- hutch_python/tests/test_ipython_log.py
- hutch_python/tests/test_log_setup.py
- hutch_python/tests/tstpython
Adds a few debug features to user space, the most important being:
- availability of debug mode, where the console logger is at level `DEBUG`
- command-line option `--debug` to start in debug mode
- `_debug_mode()` returns `True` or `False`, can be set as `_debug_mode(True)`
- `_debug_context()` to temporarily enable debug mode for a block of code
Changes:
- change `INPUT` to level 5 (less then `DEBUG`)
- group log files in directories by month
- make sure log directories have full write permissions
- can easily enable `DEBUG` prints in a session to see what is happening without repeatedly referring to a log file
- `INPUT` being below `DEBUG` allows the previous feature to be used without an input/output echo
- log files in one flat directory will be a disaster by the end of the year …
> ENH: Logging Features

- .gitignore
- hutch_python/load_conf.py
- hutch_python/tests/experiments/mfxx010.py
Make all loaded objects available from `hutchname.db`, e.g. we can now do `from mfx.db import mfx_attenuator`.
The `hutchname/db.py` file will be autogenerated and annotated.
It needs to be very very easy to track what objects are being loaded from the databases and to access them.
The tst experiment file gets objects from `tst.db`. It was also tested in a test ipython session.
Docstrings updated.
`db.py`
```
"""
The objects referenced in this file are populated by the tstpython
initialization. If you wish to use devices from this file, import
them from tst.db after calling the tstpython startup script.
hutch-python last loaded on 2018-02-08 14:16:21.154315
with the following objects:
tst_device_1         <class 'happi.device.Device'>
tst_device_2         <class 'happi.device.Device'>
daq …
```
> ENH: Easy reference to database objects

- hutch_python/tests/test_plugins/test_questionnaire.py
Clear the cache before each test.
`happi` caches devices in `pcds-dev` now, so the later tests that use the same device name are picking up the old devices in our dev build.
> TST: Fix test so it works with happi that caches devices

- hutch_python/cli.py
- hutch_python/tests/script.py
- hutch_python/tests/test_cli.py
- hutch_python/tests/test_ipython_log.py
- hutch_python/tests/test_tstpython.py
Fixes a bug introduced in #52 where the ipython embed and script run were being done in the wrong scope, so objects we loaded weren't actually available. Adds tests that address this. Simplifies and annotates these startup functions.
I noticed that `x` wasn't available in my `tstpython` session. One thing led to another...
Two major test adds:
- check if `script.py` can reference `unique_device` created in the load process
- check if `tstspython` ipython session can reference `unique_device`
> FIX: Bad User Scope

- hutch_python/plugins/experiment.py
- hutch_python/plugins/namespace.py
- hutch_python/tests/test_utils.py
- hutch_python/utils.py
Use `IterableNamespace` instead of `SimpleNamespace`.
This allows us to use statements such as `for motor in motors:` and `list(slits)`. This was low priority but it was implementable within 10mins so I just went for it.
> ENH: Add and use iterable namespaces

- conda-recipe/meta.yaml
The old one doesn't work for this module any more, so let's cut it out before we forget.
> BLD: use the newer devices module

- conda-recipe/meta.yaml
- hutch_python/cli.py
- hutch_python/daq.py
- hutch_python/plan_defaults.py
- hutch_python/tests/test_cli.py
Use `pcdsdaq.Daq` instead of `pcdsdevices.Daq`
API change in our other libraries to make room for more daq-related objects later
> ENH: Switch to pcdsdaq for Daq class

- hutch_python/load_conf.py
Slice the experiment name differently so that we can support proposals that are three characters long (like the detector experiment 111).
We used to assume a form `hhhpppprr`, where h is hutch p is proposal and r is run, but now we only assume a three-letter hutch at the start and a two-digit run at the end.
closes #65
> FIX: Allow proposals of variable length

- hutch_python/happi.py
- hutch_python/qs_load.py
- hutch_python/tests/conftest.py
- hutch_python/tests/test_happi.py
- hutch_python/tests/test_questionnaire.py
If either the Questionnaire or main happi database is empty we should warn the
user specfically instead of generating a non-sensical error messages. This is
mainly caused by the fact that `.all_devices` and `.search` return `None`
instead of empty lists
Closes #44
> FIX: Catch empty happi databases

- hutch_python/constants.py
Add entries in constants for each hutch's configured daq platform.
Note: I haven't dealt with the cxi 2-daq problem yet, but it's easy do something like:
```
from cxi.db import daq
daq._plat = 3
```
In the beamline file, so if we haven't figured that out before launch day it is ok
closes #72
We want the `daq` to work for all hutches.
> ENH: Add platforms for current hutches

- conda-recipe/meta.yaml
- hutch_python/cli.py
Make sure `matplotlib` is fully configured in a default IPython shell.
1. `IPythonShell.enable_matplotlib`
2. `plt.ion()`
Might be a different way around this, but it seems to work. Downside is `matplotlib` is now an actual dependency.
Closes #75 
There was no test added. I think this is a simple enough fix that would have a strange enough test it isn't worth the development time. Something is possible using `plt.get_fignums` to check for open figures, didn't spend the time to investigate if this works in Travis or not.
https://stackoverflow.com/questions/3783217/get-the-list-of-figures-in-matplotlib/15900439#15900439
> ENH: Enable matplotlib

- hutch_python/log_setup.py
Deliberately ignore parso logging messages as they are produced on every tab completion attempt. This could be reverted if a community solution to https://github.com/ipython/ipython/issues/10946 is produced.
Example of annoying log messages
```
DEBUG    diff parser calculated
DEBUG    diff: line_lengths old: 1, new: 1
DEBUG    diff replace old[1:1] new[1:1]
DEBUG    parse_part from 1 to 1 (to 0 in part parser)
DEBUG    diff parser end
```
> DEV: Remove spammy parso DEBUG messages

- docs/source/experiment.rst
- docs/source/startup.rst
- hutch_python/exp_load.py
- hutch_python/load_conf.py
- hutch_python/tests/test_experiment.py
- hutch_python/tests/test_load_conf.py
- After loading ``User()``, add the questionnaire objects to it
- Load ``SimpleNamespace()`` as a fallback for a missing or malformed experiment file
- alias ``x`` to ``user``
This is a feature of the old python that is very helpful. The ``x`` or ``user`` object becomes the object that the users are allowed to call methods from during their experiment.
closes #82 
I added a check to make sure that the experiment object contained a reference to a questionnaire object.
I've added to the docs as appropriate on the startup routine page and on the experiments page. I have built the docs in my environment and they look as intended.
> ENH: Include questionnaire objects in the user object

- docs/source/utils.rst
- hutch_python/load_conf.py
- hutch_python/tests/test_load_conf.py
- hutch_python/tests/test_utils.py
- hutch_python/utils.py
- If any of the metadata namespaces has one or fewer objects contained, don't bring them to the ipython session.
- add utility function for counting the metadata namespaces
Without this fix, anything in the user's beamline file with an underscore becomes a metadata namespace!
For example, `safe_load` gets repackaged as `safe.load`, which is undesirable.
closes #78 
- added test for the utility function
- add check for `tst` object that I broke, to make sure I didn't break it
- verified in tstpython
Added to the `utils` api docs
> ENH: Don't add a metadata instance with only one object

- docs/source/hutch_setup.rst
- hutch_python/qs_load.py
- hutch_python/tests/conftest.py
Originally the configuration file was for the Questionnaire alone so it was given the specific name `qs.cfg`. In reality this information is useful for all the `pswww` applications so we should look for a more general name like `web.cfg`.
Tests are now done with `web.cfg` file
References to `qs.cfg` have been changed to `web.cfg`
> MAINT: Rename qs.cfg to web.cfg

- hutch_python/load_conf.py
- hutch_python/tests/test_load_conf.py
Use the presets recently added to `pcdsdevices`. Create the `presets/beamline` and `presets/proposalrunnum` directories.
The people have spoken. We've split between the `beamline` presets that are permanent and the `experiment` presets that are not.
Assume presets work in `pcdsdevices`, make sure we've set up the paths here.
In `pcdsdevices`
This will definitely fail on travis until we cut a new release for `pcdsdevices` with the presets.
> ENH: Set up the presets

- docs/source/environment.rst
- hutch_python/cookiecutter/{{ cookiecutter.hutch }}/{{ cookiecutter.hutch }}version
- Update the docs page to not refer to specific env names
- Update cookie-cutter to pick the upcoming latest (`pcds-1.0.0`)
> BLD: Prepare for new default environment

- hutch_python/load_conf.py
- hutch_python/namespace.py
- hutch_python/tests/test_namespace.py
- Copy the load cache's namespace instead of spidering out and constructing a new one
- Recursively run through class definitions for ophyd subdevices instead of through object getattrs, skipping lazy components and caching classes we've seen.
Unfortunately, this made the code more confusing to follow.
Class namespace loading is really slow with lazy devices, especially if the branching tree is too large, due to the recursive calls. This speeds up the process considerably by inspecting the classes instead of the objects and recording a small list of which attributes to grab from each class.
closes #103 
Added tests and confirmed on a dev checkout of mfx repo, it no longer stalls or errors. I might want to add an additional test, we'll see.
> ENH: Optimize class namespaces

- hutch_python/happi.py
- hutch_python/tests/test_happi.py
Use the `lightpath` config to check what the upstream beamlines are and the range we care about them. From this we can load **all** the upstream devices along the beamline not just those with the same name as the hutch.
This does not work quite right with XCS. We need to tell it to load **both** the `PBT` and standard `XCS` paths. I'm not sure the best way to complete this task. Tempted to just load the few devices on the `PBT` from `happi` but in the `beamline.py` file ....
Closes #69 
Added a test where we load only upstream devices. Tested this in `MFX` and everything worked exactly as it should.
> ENH: Load upstream devices

- hutch_python/bug.py
- hutch_python/tests/conftest.py
- hutch_python/tests/test_bug.py
Use of a proxy is necessary to allow posts from hutch machines. This information  about the proxy host and port can be specified in the `web.cfg` fille.
Closes #110 
Closes #111 
* Tested using actual proxy host from hutch machine
* Add a test to make sure proxy information is properly collected from `cfg` file
Added an example of proxy specification to `report_bug` docstring
> ENH: Allow proxy host in report_bug

- hutch_python/constants.py
I had a typo when setting up the hutch color map. CXI ended up being an ugly grey instead of a nice red. All other hutch colors are correct.
> FIX: cxi was the wrong color

- hutch_python/cli.py
Weird bug where the jedi completion gives an extra `mro` function for `SimpleNamespace` instances... so everytime you do `namespace.<tab>` you get a bogus `mro` that isn't actually an attribute of the class. I expect someone is being too zealous in including class-only methods.
This quick shell mod restores normal completion behavior.
> FIX: disable jedi in ipython shell

- hutch_python/cache.py
- hutch_python/tests/test_cache.py
Fix issues with importing from `hutchname.db`
closes #121 
Added a test, and the patch is currently helpful in starting up the xcs directory
> FIX: db import

- hutch_python/load_conf.py
- hutch_python/namespace.py
- hutch_python/tests/test_namespace.py
- Stop using happi md to build the tree
- Use only the names
https://github.com/pcdshub/Bug-Reports/issues/2
I was trying to resolve this issue, and I found it to be extremely unwieldy to partially match metadata and names... And there was a lot of extra code for stripping the names but only if the name matched the metadata, etc... So why not simplify the whole process? This is much simpler code to follow and much easier for a user to take advantage of and manipulate.
Modified the tests and checked in mfx
Probably should be added explicitly in the docs, but the docstrings have been updated.
> API: Simplify metadata_namespace into tree_namespace

- hutch_python/cookiecutter/{{ cookiecutter.hutch }}/.gitignore
Noticed this was missing while setting up xcs
> ENH: Add logs to cookiecutter gitignore

- hutch_python/exp_load.py
Parse the `ImportError` for `module_name`
closes #125 
Reviewing this code snippet, I wonder if the experiment file should use a different logging mechanism for errors. Perhaps this is the one place where the user wants to see the traceback? Perhaps also in beamline.py?
> FIX: Use the normal erroring mechanism for ImportError inside the file

- hutch_python/namespace.py
- hutch_python/tests/test_namespace.py
If we're constructing the tree namespace and we encounter a leaf that already exists, we need to handle it properly. Currently it can fail and break the tree. This makes it show a warning message about two devices having a naming conflict.
xcspython load has a conflict between `xcs_lodcm` and `xcs_lodcm_yag`
I have added a test.
> FIX: Duplicate names in tree_namespace

- docs/source/releases.rst
- hutch_python/cli.py
Check that we have a `DISPLAY` environment variable before configuring the `matplotlib` backend for `IPython`. This destroys the entire session which is strange. We should allow users without displays to access non-graphics functions. A warning is printed to the terminal that alerts the user they don't have a configured `DISPLAY` so they will be aware something is strange.
Just for fun, I tried seeing what would happen if I ran a `bluesky` scan with `BestEffortCallback` to see if it exploded without `matplotlib`. This seems to error nicely and print an error that is consistent with our warning.
```python
RuntimeError: Invalid DISPLAY variable
```
We could be extra nice and not configure the `BEC` for non `display` users but this seems extreme to me.
As a fix for …
> MAINT: Do not install matplotlib backend without DISPLAY

- hutch_python/load_conf.py
This causes a big logging error later if we have an empty path.
> FIX: only have the beampath if there were devices in the path

- docs/source/experiment.rst
- docs/source/start.rst
- hutch_python/cli.py
- hutch_python/exp_load.py
- hutch_python/load_conf.py
- hutch_python/tests/experiments/x011.py
- hutch_python/tests/test_load_conf.py
- hutch_python/tests/test_questionnaire.py
`hutch-python --exp cxilp4517` or `hutch-python --exp lp4517` can be used to override the experiment for a single hutch python session.
closes #140 
Added tests and tried it for xpp
Added to the docs appropriately. It will also get into the `--help` string and the `--help` string in the docs automatically.
> ENH: exp cli arg

- bin/hutch-python
- conda-recipe/meta.yaml
- hutch_python/bug.py
- hutch_python/cli.py
- hutch_python/ipython_log.py
- hutch_python/tests/test_cli.py
- hutch_python/tests/tstpython
- Switch from `IPython.embed` to `IPython.start_ipython`
- Clean up the launcher
- `import` statements and other simple things don't work how you expect in the `embed` terminal: essentially, normal statements never touch the global scope. This means that things like function and class definitions in this `ipython` terminal have no access to interactively invoked imports etc.
- `start_ipython` is the officially supported way to launch interactive terminals, while `embed` is just a debugging tool
- `start_ipython` opens up the possibility of doing things in the normal `ipython` way e.g. normal config files, ipython extensions, etc.
- The old launcher code was completely unreadable, this is more sane
It seems to work 100%, after making this PR I'll do some testing runs with a live hutch
No …
> FIX: Launch IPython Correctly

- conda-recipe/meta.yaml
- hutch_python/load_conf.py
Loaded and cached archapp in load_conf.py to run in hutch python.
Add the EpicsArchiver interface to new beamline python.
Addresses #86 
@ZLLentz  is testing it now.
Labeled it in load_conf.py
> Stuff archapp into load_conf.py

- conda-recipe/meta.yaml
- hutch_python/load_conf.py
- hutch_python/tests/test_load_conf.py
`using_fake_epics_pv` was removed from `ophyd`, but it was not needed here so we remove it as well.
Switch to requiring the "next" version of `pcdsdevices` which will be compatible with the newest `ophyd`.
Everything else is taking care of misc warnings
we are going to 1.4
Note to self: rerun test once `pcdsdevices` `v1.3.0` is tagged. The tests passed locally.
> MNT: Ophyd 1.4 and cleanup

- docs/source/debug.rst
Should only be merged after #185 , this adds some notes about what the logger is and how it could be used.
This will be in place of a confluence document, as I found that hutch-python documentation linked back to github.
In isolation, I'm having more trouble than usual forming coherent sentences, so suggestions/corrections are very welcome here.
> DOC: add some notes about the PCDS-wide logger

- hutch_python/log_setup.py
Quiet down various loggers that have decided to make INFO their personal high-priority debug streams.
closes #190 
Super spammy on startup and during bluesky scans, and always if you imported any ophyd sim devices...
I will bring this into the pcdsutils soon (probably)
> MNT: make loggers behave more quietly

- .travis.yml
- conda-recipe/meta.yaml
- dev-requirements.txt
- Build docs even if we don't upload
- Put `conda-forge` first for better results
- Pin latest of in-house dependencies
- The tag failed because the docs don't build.
- The docs failure was missed because they weren't being built except on tag.
- The docs failed because they were running with old versions of libraries.
Truthfully there is more to be done here but this was good enough to fix the problem for now
> MNT: Fix the docs build to fix the tag

- conda-recipe/meta.yaml
- hutch_python/cam_load.py
closes #161 
I didn't check this at all, hopefully nothing broke. If it did it's probably just testing infrastructure. This probably won't build until pcdsdevices is tagged.
> API: ending : in area detector prefix

- .travis.yml
- hutch_python/tests/conftest.py
Pyepics/ophyd combination currently freezes at close due to a pyepics bug. This makes tests hang at the end if they don't do dumb monkeypatches.
The test hanging has a knock-on effect where it causes the test to fail the "big" pcds-envs test. This is because pcds-envs assumes it will take less than 5 minutes to run each test suite. This is reasonable because there are many packages to test, and if they take forever to run it will overrun the max duration of a travis build.
> TST: Cleanup Freeze Workaround

- hutch_python/load_conf.py
- hutch_python/tests/test_load_conf.py
Rather than pass every camviewer area detector into the user's ipython shell, collect them into a `SimpleNamespace`
This avoids name conflicts between devices defined in camviewer and devices defined in happi
Worked at XPP, almost certainly busts this repo's test suite.
> MNT: pack camviewer into namespace to avoid name conflicts

- hutch_python/cli.py
Turns off engineering mode and adds `set_engineering_mode()` to the default namespace following @ZLLentz's suggestions.
Although it works, I expected there to be a lot fewer items in the tab-complete list with engineering_mode off. I'm guessing there's some tweaking we gotta do in `pcdsdevices`.
Fixes #188
Hacked `xcspython` to run this version instead and it comes up with engineering mode off and with the function in the namespace
There's a brief comment
> ENH: Turn off engineering mode by default

- .pre-commit-config.yaml
- hutch_python/constants.py
- hutch_python/ipython_log.py
- hutch_python/log_setup.py
- hutch_python/tests/test_log_setup.py
Closes #219 
Uncaught exceptions in a hutch-python environment will be shipped off to logstash with this PR.
These would just be spammy and are ignored:
* `KeyboardInterrupt`
* `SystemExit`
> ENH: ship uncaught exceptions off to logstash

- hutch_python/cli.py
Referring to https://ipython.readthedocs.io/en/stable/config/options/terminal.html, update our jedi disabling config appropriately.
- `use_jedi` makes tab completion very slow, and it is unclear that it helps in a hutch-python session, so we don't want it.
- Extra items in the IPython config are silently ignored, so it's ok to cover for both APIs
- closes https://github.com/pcdshub/Bug-Reports-and-Requests/issues/39
Only interactively- I could not see a way to open the IPython terminal in a unit test and have it not break the test suite.
N/A
> MNT: disable jedi three times for good luck

- conda-recipe/meta.yaml
- hutch_python/load_conf.py
Continuation of https://github.com/pcdshub/pcdsdaq/pull/87
New argument added, let's use it! This will make the DAQ usage more snappy without having any local hotfixes.
> MNT: pass hutch_name to Daq to avoid calling get_hutch_name

- hutch_python/load_conf.py
Use `ophyd.PositionerBase` as the base for the motors group so that we accumulate all motors, not just `pcdsdevices` `EpicsMotor` objects.
Hotfix from dev hutch-python common
Runs in dev
> MNT: expand motors group to have all positioners

- hutch_python/load_conf.py
See title. This kicker used to make the live plot updates work, but is now deprecated in favor of the qt teleporter that we're already using here.
Warning about this comes up when you start hutch-python.
It has not, but this function verifiably does nothing:
https://github.com/bluesky/bluesky/blob/9f7efffa84009bf4b2ab6324f30aa338402c27d1/bluesky/utils.py#L914
> MNT: remove deprecated qt kicker that does nothing

- hutch_python/utils.py
Time safe_load and report duration
```
INFO     Loading daq...
ERROR    Failed to load daq after 0.00 s
INFO     Loading archapp...
SUCCESS  Successfully loaded archapp in 0.00 s
INFO     Loading default groups...
SUCCESS  Successfully loaded default groups in 0.30 s
```
To help identify which parts of the main load chunk are slow
https://github.com/pcdshub/Bug-Reports-and-Requests/issues/34#issuecomment-702953233
Ran it locally one time and fixed a typo
> ENH: time safe_load and report duration

- conda-recipe/meta.yaml
- hutch_python/load_conf.py
- hutch_python/tests/test_load_conf.py
Apply hotfix from dev/deployed hutch-python, add a comment for context.
This is the (dangerous) namespace that lets you do:
`xpp.ccm`, for example, instead of `xpp_ccm`. It creates these big cascading namespaces of devices.
Tree namespace can cause havoc and break top-level devices
See #224, #159 
No complaints from its omission (yet) in dev/deployed hutch-python
> MNT: disable tree namespace until issues are resolved

- hutch_python/exp_load.py
- hutch_python/tests/test_experiment.py
- hutch_python/tests/test_user_load.py
- hutch_python/user_load.py
- hutch_python/utils.py
Any exception raised while loading the user file will cause every other importable device/function/etc to not appear in the overall hutch-python user namespace.
Instead of continuing with a small and easy to skip message, this PR adds the functionality of querying the user to continue.
Closes #192 
Interactively.
```
INFO     Loading klauer.beamline...
klauer beamline
ERROR    Failed to load klauer.beamline
Traceback (most recent call last):
File "/Users/klauer/Repos/hutch-python/hutch_python/user_load.py", line 37, in get_user_objs
module_objs = extract_objs(module)
File "/Users/klauer/Repos/hutch-python/hutch_python/utils.py", line 169, in extract_objs
scope = import_module(scope)
File "/Users/klauer/mc/envs/lucid/lib/python3.6/importlib/__init__.py", line 126, in import_module
return …
```
> ENH: query the user if their beamline config fails to load

- hutch_python/cli.py
- hutch_python/tests/test_cli.py
Tab completion should filter undesirable items outside of engineering mode, regardless of the Jedi configuration.
Closes https://github.com/pcdshub/pcdsdevices/issues/709
Locally, checking tab completion with IPython.
Just added a quick test, but it may be fragile depending on IPython's API changing.
Just in the issue. It's really an implementation detail (hack).
> HACK/FIX: IPython tab completion without Jedi

- hutch_python/happi.py
- Remove the check for device z location in the happi loader
- Remove the undocumented configuration for start/end of beamline z
- Frequently causes confusion: why are my devices not loading?
- Redundant behavior with the "active" tag
- closes #247 
Still passes regression tests
This is fixing a bug basically- the z behavior was not documented, so the documentation matches the code better after this change.
> MNT: remove the z check in happi loading

- conda-recipe/meta.yaml
- hutch_python/plan_defaults.py
- In addition to the bluesky built-ins, include our plans in the standard loader too
- Remove the pcdsdaq preprocessor that was moved to nabs
- It should be easy to find the tested plans in the interactive sessions
- closes #255 
Checked for every single nabs plan, and did a spot-check of the bluesky plans
> ENH: Include plans from nabs

- hutch_python/load_conf.py
Add the kluge from #260 in use in XPP to general hutch python loader
closes #260, though there will be follow-up work for a variety-aware `LiveTable` at some point
- A lot of values with really large or really small numbers generally display poorly with the default `LiveTable` formatting.
- Scientist request
- "g" formatting switches between scientific notation and normal numbers seamlessly as numbers get small or large
n/a
Will be in release notes
> MNT: switch LiveTable format to scientific for large/small numbers

- hutch_python/constants.py
Adds the `-H` option to the `get_current_exp` call to properly specify hutch
Fixes #265 
Interactively
It hasn't
> MNT: Adjust get_current_exp args to specify hutch

- docs/source/releases.rst
- hutch_python/cache.py
- hutch_python/exp_load.py
- hutch_python/load_conf.py
- hutch_python/plan_defaults.py
- hutch_python/tests/test_utils.py
- hutch_python/utils.py
Useful tables show in IPython for our namespaces now, even recursively.
There's hooks for showing the tables - with some caveats for recursively showing tables - in HTML as well.
Display useful tables!
Simple tests in the suite.
Docstrings and release notes.
<details>
<summary>Recursive output</summary>
```
In [1]: all_objects
Out[1]:
This HelpfulNamespace has the following attributes available:
+------------+--------------------+-----------------------------------------------------------------------------------------------------------------------------+
| Attribute  |       Class        | Description                                                                                                                 |
+------------+--------------------+------------------------------------------ …
```
> ENH/REF: IterableNamespace -> HelpfulNamespace

- hutch_python/load_conf.py
- hutch_python/ophyd_settings.py
- Set the default ophyd epics signal write_timeout to 5.0 instead of no timeout (previously: wait forever)
- Explicitly pick the current ophyd defaults as the pcds defaults for the other parameters
- Nothing in LCLS needs an infinitely long write timeout
- We had problems in XCS with infinite write timeouts disrupting later signal puts (the set thread blocks if a set is already in progress)
- Explicitly opt in to finite timeouts for everything else in case some ophyd default changes to infinite in the future
- closes #273 
Ran with TMO's config to verify that it was run early enough in the chain:
```
_                   _____       _   _
| |                 |  __ \     | | | |
| |_ _ __ ___   ___ | |__) |   _| |_| |__   ___  _ __
| __| '_ ` _ \ / _ \|  ___/ | | | __| '_ \ / _ \| '_ \
| …
```
> ENH: set defaults for ophyd epics signal timeouts

- .travis.yml
- hutch_python/cli.py
- hutch_python/load_conf.py
- hutch_python/mpl_config.py
- Remove `matplotlib.use()`
- Use the environment variable as the principal way to determine the matplotlib backend
- Disable the best effort callback plotting if we don't have a qt5 backend
- Set up the hutch-python ipython session to match the same backend determined in the load process
- `matplotlib.use()` can fail if we run in a headless mode
- the environment variable falls back to `agg`, which works in headless mode
- bec fails if we don't use qt5
- ipython needs special setup for matplotlib
- interactively
- hopefully tests still pass
- will be in the release notes
> ENH: fix issues related to matplotlib setup in headless mode

- hutch_python/ipython_log.py
- hutch_python/log_setup.py
- hutch_python/tests/test_ipython_log.py
* Fix order of message logging
* Adjust exception handling output for log files and centralized logger
* Catch exceptions in threads
* Also set `sys.excepthook` - but I believe this doesn't do anything here
Open for any/all input here, and also if you know any better for the last point above.
Closes #281 
* Local testing
* Updated test suite
Sample log from session file (slightly outdated, but the idea is there):
```python
Exception in IPython session in thread <Thread(Thread-3, started daemon 123145393176576)>. Last input line 0:
[n/a]
Exception details:
Traceback (most recent call last):
File "/Users/klauer/mc/envs/lucid/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/Users/klauer/mc/envs/lucid/lib/python3.8/threading.py", line 870, in run …
```
> REF/FIX: logging order, missed exceptions, etc.

- hutch_python/constants.py
- hutch_python/log_setup.py
- hutch_python/utils.py
Log to centralized server only when on a PCDS host.
Closes #278 by an alternative and easier method
Without this patch, you may see errors or messages intended for the centralized logger in the terminal:
```
Line: 1
Input: asdf
Exception: NameError: name 'asdf' is not defined
Traceback (most recent call last):
File "/Users/klauer/mc/envs/lucid/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "<ipython-input-1-7d97e98f8af7>", line 1, in <module>
asdf
NameError: name 'asdf' is not defined
```
Locally
Log tests still pass. Need to investigate on a PCDS machine to fully verify the solution.
> REF/FIX: log only when on PCDS hosts

- hutch_python/__main__.py
- hutch_python/ipython_log.py
- hutch_python/log_setup.py
* Add `stacklevel` kwarg to centralized exception logger
* Unrelated bonus: allow hutch-python to be run by way of `python -m hutch_python`
* `stacklevel` allows us to describe where in the stack the log message should be reported to come from
* `stacklevel=1` means it comes from the caller of `logger.log()`, whereas `stacklevel=2` means it comes from the caller's caller
Mostly interactively.
A quick demonstration of `stacklevel` looks like:
```python
{'stacklevel': 1}
2021-07-22 11:14:05,297 - PID 96716       log_setup.py: 596 log_exception_to_central_server ERROR    [exception] testing
Traceback (most recent call last):
File "/tmp/test.py", line 15, in inner
raise ValueError("testing")
ValueError: testing
```
```python
{'stacklevel': 2}
2021-07-22 11:14:05,297 - PID 96716 …
```
> ENH: support stacklevel for centralized logging on Python 3.8+

- .travis.yml
- conda-recipe/meta.yaml
- hutch_python/cli.py
- hutch_python/tests/test_load_conf.py
- requirements.txt
~Pending https://github.com/pcdshub/archapp/pull/15~
* Bumped archapp version to pick up fixes
* Conda tests on latest as we need pcdsdevices (now >=3.9)
* Minimal set of fixes for pypi-based testing to work
* archapp fixed up, xfails removed
* Test assumed lightpath was installed, tweaked it if not
* Addresses #290 but doesn't fix it per se
* Should add an additional argument to set 'base' and 'env', I think, if conda isn't installed
See test suite
See this PR text
> CI: conda tests on 3.9; fix pypi-based testing

- hutch_python/load_conf.py
- hutch_python/log_setup.py
- hutch_python/logging.yml
- hutch_python/tests/test_log_setup.py
Functionality proposal, at least.
* Add in the possibility of automatically filtering out ophyd loggers based on the number of messages they emit
* Done on a per-object basis, in periods of 1s, 10s, and 60s.
* Escape-hatch on a per-object basis as well
* Our ophyd object definitions are imperfect
* We can and will fix noisy log messages, but they can be crippling for end-users
I think this proposal:
* Gives users an additional hook to catch new things that arise and still finish their experiments
* Gives us a bit of room to fix our imperfect devices more at our leisure
* Could be done in addition to other things
Bonus: closes #296 
Related: #297 
Interactively, for now
Pending agreement
```python
In [3]: for i in range(200): sim.fast_motor2.log.warning("test")
...
INFO     _count_update - …
```
> ENH: record and optionally filter noisy ophyd loggers

- hutch_python/log_setup.py
- hutch_python/logging.yml
* Add ability to disable log-hushing filter thresholds (threshold count <= 0)
* Configures "debug" (file) handler's object filter separately from the console one
* Debug object filter disables logger silencing (-> file gets full set of messages regardless of the console)
Addresses #307 but may not close it - we need some real testing at the beamline.
Locally
Docstrings and config files.
> ENH: threshold disable; adjust object filter settings for file

- docs/source/releases.rst
- hutch_python/logging.yml
Set noisy logger default thresholds to 0, disabling them.
The functionality is just too confusing. We could try to rip out the contents at some point, but for now this should suffice.
Closes #307
> MNT: disable noisy logger detection by default

- hutch_python/load_conf.py
Switch the LCLS2 DAQ connection/message timeout from 1s to 10s.
Some operations are expected to take longer than 1s occasionally, but not quite 10s.
Live in RIX
Probably doesn't break any tests
Release notes later
> MNT: expand lcls2 daq default timeout

- hutch_python/constants.py
Add `"daq_type"` and `"daq_host"` to the list of `VALID_KEYS`.
This list of keys is used to help validate the `conf.yml` file. We're currently getting false warnings in the initial startup from these in the lcls2 hutches.
Live in RIX
Tests probably still pass
Not yet, it will be in the release notes as a bugfix
> BUG: expand VALID_KEYS for the new keys we've added

- hutch_python/load_conf.py
* QtAgg and Qt5Agg are both valid matplotlib backends (and may have been an upstream name change with the introduction of PyQt6?)
* mfx hutch-python had bluesky plots disabled due to a backend name check failure per @ZryletTC 
It has not been tested other than in the test suite.
E-mail report of issue. ~To be made a real issue.~
Closes #315
> FIX: Qt5Agg and QtAgg are both valid

- hutch_python/cli.py
There is a feature in IPython where the user's input gets reformatted by `black` on the fly if `black` is installed, for example, adding spaces and formatting for multi-line.
This throws some exceptions at the start of the session and is really annoying in general if you're trying to up-arrow to old scans that were intended to be one-liners, etc.
This has been a feature in IPython for a while, but in versions 8.0.0 and 8.0.1 it is enabled by default.
This PR simply disables it.
See https://ipython.readthedocs.io/en/stable/whatsnew/version8.html#auto-formatting-with-black-in-the-cli
Annoying errors, annoying feature for scientific use
Interactively only
> MAINT: disable ipython's black input formatting

- docs/source/releases.rst
- hutch_python/cli.py
- hutch_python/load_conf.py
- hutch_python/tests/test_utils.py
- hutch_python/utils.py
Makes a new Sigint handler that aborts the RunEngine rather than requesting a pause. 
Registers this as a context_manager at RunEngine initialization
Fancy threaded tests to actually send this signal within pytest
Various beamline scientists requested Ctrl+C abort the current run and ready the RunEngine by default, rather than pausing.  
[Jira](https://jira.slac.stanford.edu/browse/LCLSECSD-525)
There are other signals available to Unix operating systems, but I'm still looking into how to activate those.
Interactively, tests pass locally
This PR.
> ENH: Changes default Ctrl+C behavior to abort

- hutch_python/cli.py
- hutch_python/env_version.py
Print environment information at hutch python startup.  
With the variation in environments used around the facility, it'd be good to expose exactly what's being used when hutch-python is started.  
Interactively.
In this PR
> ENH: output environment info at startup

- docs/source/releases.rst
Includes #342 and #337 
We might want/need to accompany this upcoming conda env with some guidance on how to set up the tab completion configuration- maybe links to the relevant documentation will be sufficient.
> DOC: write release notes for v1.16.0

- hutch_python/ipython_log.py
- hutch_python/tests/conftest.py
Show source of exception in facility log message summary, such as:
(from user input)
```
2022-07-13 15:44:44	
In [2]: abc()
Exception: ValueError: this is the exception message
File: /cds/home/k/klauer/Repos/hutch-python/raiser.py line 9
```
(from a thread - showing the closest input number)
```
2022-07-13 15:44:44	
Thread: Thread-51
Last user input [2]: abc()
Exception: RuntimeError: this is the exception message
File: /cds/home/k/klauer/Repos/hutch-python/raiser.py line 5
```
The current message is insufficient to get an idea of what happened (from Grafana):
```
2022-07-13 12:40:28	
Line: 31
Input: tmo_laser.lens_z.limits()
Exception: TypeError: 'NoneType' object is not callable
```
~pcdsutils will need an update to include this information in the JSON sent to logstash as well.~
Related …
> ENH: show file/line in facility log message

- hutch_python/tests/conftest.py
- hutch_python/tests/test_bug.py
- hutch_python/tests/test_log_setup.py
Some of the tests fail on psbuild in the latest conda environment, but not on travis CI. This PR will make the test suite run on our local servers, adjusting the test suite as appropriate.
We need to make sure these aren't real bugs. The automated suite missing failures is scary.
- `test_bug` tests a feature that has not been used in more than a year: posting to https://github.com/pcdshub/Bug-Reports-and-Requests/issues. It fails on recent versions of ipython when running on real computers. It passes on CI because it hits a caught exception first that we ignore because we're expecting it to happen on CI only. To fix this function we need to understand a bit better how the ipython session numbers work which is opaque (I tried for a bit). It's more prudent to move on and replace this with …
> TST: address failing tests on psbuild

- .pre-commit-config.yaml
- .travis.yml
- docs/source/upcoming_release_notes/356-ensure_endstation_devices.rst
- hutch_python/happi.py
Add the endstation name to the beamlines to load set.
It's possible for this to be missing if the hutch's own beamline isn't in its lightpath.
This is... rare? Or maybe it only happens due to a misconfiguration?
Whatever the case, it's an edge case to cover.
In most cases, this won't do anything because the hutch name should already be in the set.
Interactively only via getting cxi devices to load again.
Release notes only
> FIX: ensure endstation devices are always loaded

- .github/PULL_REQUEST_TEMPLATE.md
- docs/source/upcoming_release_notes/373-mnt_strip_prefixes.rst
- hutch_python/cam_load.py
- hutch_python/tests/camviewer.cfg
Strips whitespace from PV's found in camviewer.cfg during the `cam_load` process
Closes #372 
added a space to the test suite's camviewer.cfg, and tests still pass
This PR
> MNT: strip whitespace when gathering detector prefixes

- docs/source/upcoming_release_notes/379-enh_limit_devices.rst
- docs/source/yaml_files.rst
- hutch_python/constants.py
- hutch_python/happi.py
- hutch_python/load_conf.py
- hutch_python/tests/happi_db.json
- hutch_python/tests/test_happi.py
Adds `load_level` as a conf.yaml key that allows hutches to choose how many ophyd devices get loaded.  Currently includes 3 options:
- ``UPSTREAM``: The hutch's devices, and devices upstream from the requested hutch.
If there are multiple paths to the requested hutch, all paths' devices are loaded.
- ``STANDARD``: Devices gathered via ``UPSTREAM``, plus devices that share the
"beamline" field in happi with the ``UPSTREAM`` devices.  (The current standard)
- ``ALL``: All devices in the happi database.  Use this option at your own risk.
https://jira.slac.stanford.edu/browse/ECS-5079
Summary: We found that some hutches were loading many irrelevant devices.  TMO was catching CXI devices, XPP was catching XRT devices, etc.  This was found to be a result of the beamline field matching …
> ENH: add option to limit devices loaded via `load_level` conf.yaml key

- .gitignore
- docs/source/upcoming_release_notes/381-maint_ipython_history.rst
- hutch_python/cli.py
- hutch_python/tests/test_cli.py
Main changes:
- Add a --hist-file cli argument
- Default the history file to `/u1/${USER}/hutch-python/history.sqlite` (local disk)
- Previously: normal IPython history per user home directory on NFS
- Add a unit test
Minor changes:
- Make the cli args type-hinted
- Fix some minor styling inconsistencies
https://jira.slac.stanford.edu/browse/ECS-5096
- On NFS for some of our endstations, there are some file locking issues related to the ipython history file.
- Bringing it off of NFS should theoretically alleviate the issues, at the cost of fracturing history per-host.
- Use CLI over cfg file because this would hypothetically need to be configured per-session, whereas the cfg file is shared between all sessions for one hutch.
- Interactively as me
- Unit tests
- Tested as xcsopr and it …
> MAINT: IPython history file per host + configurable

- .github/workflows/standard.yml
- docs-requirements.txt
- docs/source/upcoming_release_notes/386-maint_numpy2_pypi.rst
Force the pypi builds to run with numpy<2
Some of these builds are failing to no fault of their source PRs.
It worked on pcdsdevices
Here only
> CI: temporarily drop numpy to under 2 in pypi builds

- conda-recipe/meta.yaml
switch to base bluesky, matplotlib in conda recipe
pip builds do not seem to install qt at all, hooray.  The pip builds were also not broken, so don't modify them here
Fix broken conda builds. 
CI, though things won't be fixed until pcdsdevices is sorted
This PR
> BLD: switch to bluesky-base, matplotlib-base in conda recipe

- docs/source/upcoming_release_notes/389-fix_elog_replaced_issue.rst
- hutch_python/startup_script.py
This comes from a hotfix in rix3 that I added onto here.
There is a niche issue where "something" gets loaded as the `elog` but it isn't a valid elog object. Then, this script picks up the non-elog item and passes it to the `ElogPoster`, which starts causing an issue (text spam? I don't quite remember) when you try to run a scan later.
This PR rearranges the error reporting a bit and includes a check that the expected objects haven't been replaced.
- Working through hotfixes as part of https://jira.slac.stanford.edu/browse/ECS-6333
- Can cause an annoying error spam if the user makes an `elog` object, instead just fail the `ElogPoster` in red text
Interactively only, checking the error messages
Here only
> FIX: more error handling for ElogPoster

- docs/source/upcoming_release_notes/391-tst_path_consistency.rst
- docs/source/yaml_files.rst
- hutch_python/tests/conf.yaml
- hutch_python/tests/test_cli.py
- fixes a quick bug that manifests depending on where you run pytest.  
- pytest is meant to be run from the repository root, but can also run from inside the test folder. 
- `test_create_arg` expected pytest to be invoked from the repository root, and would fail if run from elsewhere
- we should still advocate for running from the repository root, but it doesn't hurt to be less fragile
- includes an ascii map for the mock beamline defined in `happi_db.json`.
- Included this in the conf.yaml because json doesn't support comments
- Fixes some stray formatting errors in the github.io docs
Uncovered while helping Jane debug some unit tests. 
By ensuring the test suite still works
This PR
> TST: update path consistency, adjust documentation

- docs/source/upcoming_release_notes/297-ECS-6432_Add_ability_to_ignore_specific_upstream_devices_in_load.rst
- docs/source/yaml_files.rst
- hutch_python/constants.py
- hutch_python/happi.py
- hutch_python/load_conf.py
- hutch_python/tests/test_happi.py
Added a new feature that lets hutches exclude specific upstream devices when loading.
Refactored parts of `get_happi_objs()` function, so it's only necessary to check the `containers` variable once at the end of the function and removed specific upstream devices from `containers`.
Allows user to exclude specific upstream devices when loading, so they don't need to see irrelevant information.
https://jira.slac.stanford.edu/browse/ECS-6432
Tested manually and with unit tests.
In release notes.
> Ecs 6432 Add ability to ignore specific upstream devices in load

- .pre-commit-config.yaml
- conda-recipe/meta.yaml
- docs-requirements.txt
- docs/source/upcoming_release_notes/394-perf_defer_preset_loading.rst
- hutch_python/load_conf.py
- requirements.txt
- Utilizes https://github.com/pcdshub/pcdsdevices/pull/1317 to defer preset loading
We want to defer preset loading for performance reasons.
This will fail tests until the corresponding pcdsdevices PR is merged.
I was using this to test presets while developing https://github.com/pcdshub/pcdsdevices/pull/1317
This PR
Left: Before, Right: After
In getting that screenshot I ran into a variety of load times, preset deferral was always better but by varying margins.  
Ran on a clone of XCS's hutch-python profile, copied into my dev area
> PERF: delay preset loading for hutch-python

- docs/source/upcoming_release_notes/401-tst_hist_timeouts.rst
- hutch_python/tests/test_cli.py
- attempt to figure out why history file tests are failing
This test has been timing out on python3.12 and I want to find out why.  Perhaps splitting it out will help de-conflict things
See [this failure](https://github.com/pcdshub/hutch-python/actions/runs/14868053395/job/42239473756#step:17:510)
Locally splitting the single history file test case into 3 separate tests resulted in each taking around 7s.  With a timeout of 30s, it makes sense that this sometimes fails.  (prior to this change, that test was taking ~23s)
I re-ran the ci python 3.12 conda tests multiple times, and it's passed each time 🤷 
Interactively, with little success in reproducing the failures seen on CI
This PR
> TST: fix hist file test timeouts
